### ISSUE TITLE
🧪 テスト自動化強化: E2EテストとCI/CDパイプライン改善

### ISSUE THREAD

**Issue by 4tk666** [4tk666/next-todo#89]
## 問題の概要
現在のアプリケーションにはテストの自動化が不十分で、特にE2Eテストやビジュアルリグレッションテストが実装されていません。継続的インテグレーション（CI）パイプラインでのテスト実行も改善が必要です。

## 発見された問題
- E2Eテストが未実装（ユーザージャーニー全体のテストがない）
- ビジュアルリグレッションテストの不足
- CI/CDパイプラインでのテスト自動化が不十分
- テストカバレッジレポートの不足
- 統合テスト環境の未整備

## 影響
- デプロイ時のリスク増大
- UI/UX変更時の意図しない破綻の検出困難
- 品質保証プロセスの手動依存
- 開発速度の低下（手動テスト時間）

## 修正提案
1. PlaywrightまたはCypressを使用したE2Eテスト実装
2. Storybookを使用したコンポーネントテストとビジュアルテスト
3. GitHub Actionsでのテスト自動化改善
4. テストカバレッジレポートの設定
5. テスト用データベースセットアップの自動化

## 関連ファイル
- `.github/workflows/` 配下のワークフローファイル
- `tests/e2e/` (新規作成予定)
- `tests/integration/` (新規作成予定)
- `.storybook/` (新規作成予定)
- `playwright.config.ts` (新規作成予定)

### E2Eテスト設定（Playwright）
```typescript
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './tests/e2e',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: 'html',
  use: {
    baseURL: 'http://localhost:3000',
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
  },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
    },
  ],
  webServer: {
    command: 'pnpm dev',
    url: 'http://localhost:3000',
    reuseExistingServer: !process.env.CI,
  },
});
```

### E2Eテスト例
```typescript
// tests/e2e/todo-management.spec.ts
import { test, expect } from '@playwright/test';

test.describe('Todo Management', () => {
  test.beforeEach(async ({ page }) => {
    // テストユーザーでログイン
    await page.goto('/login');
    await page.fill('[data-testid="username"]', 'test@example.com');
    await page.fill('[data-testid="password"]', 'password123');
    await page.click('[data-testid="login-button"]');
    await expect(page).toHaveURL('/todos');
  });

  test('should create a new todo', async ({ page }) => {
    await page.fill('[data-testid="todo-title"]', 'New Test Todo');
    await page.fill('[data-testid="todo-description"]', 'Test description');
    await page.click('[data-testid="create-todo-button"]');
    
    await expect(page.locator('[data-testid="todo-item"]')).toContainText('New Test Todo');
  });

  test('should complete a todo', async ({ page }) => {
    // 既存のTodoが存在することを前提
    await page.click('[data-testid="todo-checkbox"]:first-child');
    await expect(page.locator('[data-testid="todo-item"]:first-child')).toHaveClass(/completed/);
  });

  test('should delete a todo', async ({ page }) => {
    await page.click('[data-testid="todo-delete-button"]:first-child');
    await page.click('[data-testid="confirm-delete"]');
    
    // Todoが削除されたことを確認
    await expect(page.locator('[data-testid="todo-item"]')).toHaveCount(0);
  });
});
```

### GitHub Actions CI改善
```yaml
# .github/workflows/test.yml
name: Test Suite

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Setup test database
        run: |
          pnpm prisma migrate dev --name init
          pnpm prisma db seed
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
          
      - name: Run unit tests
        run: pnpm test
        
      - name: Run integration tests
        run: pnpm test:integration
        
      - name: Install Playwright browsers
        run: pnpm playwright install --with-deps
        
      - name: Run E2E tests
        run: pnpm test:e2e
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
          
      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: playwright-report
          path: playwright-report/
          
      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
```

### Storybook設定
```typescript
// .storybook/main.ts
import type { StorybookConfig } from '@storybook/nextjs';

const config: StorybookConfig = {
  stories: ['../src/**/*.stories.@(js|jsx|mjs|ts|tsx)'],
  addons: [
    '@storybook/addon-essentials',
    '@storybook/addon-interactions',
    '@storybook/addon-a11y',
    '@chromatic-com/storybook',
  ],
  framework: {
    name: '@storybook/nextjs',
    options: {},
  },
  typescript: {
    check: false,
    checkOptions: {},
    reactDocgen: 'react-docgen-typescript',
    reactDocgenTypescriptOptions: {
      shouldExtractLiteralValuesFromEnum: true,
      propFilter: (prop) => (prop.parent ? !/node_modules/.test(prop.parent.fileName) : true),
    },
  },
};

export default config;
```

## 必要なパッケージ
```bash
# E2Eテスト
pnpm add -D @playwright/test

# ビジュアルテスト・Storybook
pnpm add -D @storybook/nextjs @storybook/addon-essentials @storybook/addon-interactions @storybook/addon-a11y @chromatic-com/storybook

# テストカバレッジ
pnpm add -D @codecov/webpack-plugin

# テストデータ管理
pnpm add -D @faker-js/faker
```

## テストデータセットアップ
```typescript
// tests/helpers/test-data.ts
import { faker } from '@faker-js/faker';
import { prisma } from '@/lib/prisma';

export async function createTestUser() {
  return await prisma.user.create({
    data: {
      email: faker.internet.email(),
      name: faker.person.fullName(),
      password: 'hashedPassword', // 実際にはハッシュ化
    },
  });
}

export async function createTestTodo(userId: string) {
  return await prisma.todo.create({
    data: {
      title: faker.lorem.sentence(),
      description: faker.lorem.paragraph(),
      userId,
      completed: false,
      priority: 'MEDIUM',
      dueDate: faker.date.future(),
    },
  });
}

export async function cleanupTestData() {
  await prisma.todo.deleteMany();
  await prisma.user.deleteMany();
}
```
